

import com.model.DrugModel;
import java.awt.GridLayout;
import static java.lang.Thread.sleep;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author rpran
 */
public class ExpiryTable extends javax.swing.JPanel {
  

    /**
     * Creates new form jpanel3
     */
    public ExpiryTable() {
        initComponents();
              CurrentDate();
    }
   
    public void Add(String Name,String Date,int i)
    {  
        DrugModel Dm = new DrugModel();
        DefaultTableModel model = (DefaultTableModel) TableExpiry.getModel();
        model.addRow(new Object[]{Name,Date,i});
    }

   
public void CurrentDate(){
         
        Thread clock = new Thread(){
        public void run(){
        for(;;){
        Calendar cal = new GregorianCalendar();
        String monthh = null;
        String dayy = null;
        int month =cal.get(Calendar.MONTH)+1;
        int year =cal.get(Calendar.YEAR);
        int day =cal.get(Calendar.DAY_OF_MONTH);
          if ((month) < 10)
        {
            monthh= "0" + month;
        }
          else 
          {
              monthh=""+month;
          }
          if (day < 10)
        {
            dayy= "0" + day;
        }
          else
              
          {
              dayy=""+day;
          }
        date_txt3.setText(year+"-"+monthh+"-"+dayy);
        int second =cal.get(Calendar.SECOND);
        int minute =cal.get(Calendar.MINUTE);
        int hour =cal.get(Calendar.HOUR);
        String houur = null;
        String minuute = null;
        String seconnd = null;
        
        if (hour < 10)
        {
            houur= "0" + hour;
        }
        else
        {
            houur=""+hour;
        }
         if (minute < 10)
        {
            minuute= "0" + minute;
        }
         else
         {
             minuute=""+minute;
         }
          if (second < 10)
        {
            seconnd= "0" + second;
        }
         else
          {
              seconnd =""+second;
          }
        time_txt3.setText(houur+":"+minuute+":"+seconnd);
            try {
                sleep(1000);
            } catch (InterruptedException ex) {
                Logger.getLogger(login_jframe.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        }      
        
        
        };
        clock.start();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        time_txt3 = new javax.swing.JLabel();
        date_txt3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableExpiry = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        panel.setLayout(null);

        time_txt3.setBackground(new java.awt.Color(255, 255, 255));
        time_txt3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        time_txt3.setForeground(new java.awt.Color(255, 255, 255));
        time_txt3.setText("Time");
        time_txt3.setRequestFocusEnabled(false);
        panel.add(time_txt3);
        time_txt3.setBounds(900, 0, 80, 20);

        date_txt3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        date_txt3.setForeground(new java.awt.Color(255, 255, 255));
        date_txt3.setText("Date");
        panel.add(date_txt3);
        date_txt3.setBounds(900, 20, 80, 20);

        TableExpiry.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Drug Name", "Expiry Date", "Days Left"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TableExpiry);

        panel.add(jScrollPane1);
        jScrollPane1.setBounds(30, 70, 860, 370);

        jButton1.setText("<<Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panel.add(jButton1);
        jButton1.setBounds(40, 10, 71, 23);

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panel.add(jButton2);
        jButton2.setBounds(120, 450, 130, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back.jpg"))); // NOI18N
        panel.add(jLabel1);
        jLabel1.setBounds(0, 0, 980, 600);

        add(panel);
        panel.setBounds(0, 0, 980, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          panel.removeAll();
        panel.setLayout(new GridLayout(1, 2));
        ExpiryAlert Ea = new ExpiryAlert();
        int i = Ea.Alert();
        jpanel4 j = new jpanel4();
        if(i>0)
        {
            j.setLabel(i);
        }
        

        panel.add(j);  
        panel.updateUI();  

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         panel.removeAll();
       panel.setLayout(new GridLayout(1,2));
       panel.add(new umedicine_jpanel());
       panel.updateUI();  
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableExpiry;
    private javax.swing.JLabel date_txt3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel time_txt3;
    // End of variables declaration//GEN-END:variables
}
