
import com.repository.RepositoryClass;
import java.awt.GridLayout;
import static java.lang.Thread.sleep;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.GridLayout;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author rpran
 */
public class viewpatient_jpanel extends javax.swing.JPanel {

    /**
     * Creates new form jpanel3
     */
    public viewpatient_jpanel() {
        initComponents();
        CurrentDate();
    }

    public void CurrentDate() {

        Thread clock = new Thread() {
            public void run() {
                for (;;) {
                    Calendar cal = new GregorianCalendar();
                    String monthh = null;
                    String dayy = null;
                    int month = cal.get(Calendar.MONTH) + 1;
                    int year = cal.get(Calendar.YEAR);
                    int day = cal.get(Calendar.DAY_OF_MONTH);
                    if ((month) < 10) {
                        monthh = "0" + month;
                    } else {
                        monthh = "" + month;
                    }
                    if (day < 10) {
                        dayy = "0" + day;
                    } else {
                        dayy = "" + day;
                    }
                    date_txt6.setText(year + "-" + monthh + "-" + dayy);
                    int second = cal.get(Calendar.SECOND);
                    int minute = cal.get(Calendar.MINUTE);
                    int hour = cal.get(Calendar.HOUR);
                    String houur = null;
                    String minuute = null;
                    String seconnd = null;

                    if (hour < 10) {
                        houur = "0" + hour;
                    } else {
                        houur = "" + hour;
                    }
                    if (minute < 10) {
                        minuute = "0" + minute;
                    } else {
                        minuute = "" + minute;
                    }
                    if (second < 10) {
                        seconnd = "0" + second;
                    } else {
                        seconnd = "" + second;
                    }
                    time_txt6.setText(houur + ":" + minuute + ":" + seconnd);
                    try {
                        sleep(1000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(login_jframe.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }

            }

        };
        clock.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        time_txt6 = new javax.swing.JLabel();
        date_txt6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TextAge = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TextAllergy = new javax.swing.JTextField();
        TextContactNo = new javax.swing.JTextField();
        TextAddress = new javax.swing.JTextField();
        TextOpno = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TextDateOfAdmission = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        TextFName = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        TextFContactNo = new javax.swing.JTextField();
        TextSex = new javax.swing.JTextField();
        TextName = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        Error = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();

        setLayout(null);

        panel.setLayout(null);

        time_txt6.setBackground(new java.awt.Color(255, 255, 255));
        time_txt6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        time_txt6.setForeground(new java.awt.Color(255, 255, 255));
        time_txt6.setText("Time");
        time_txt6.setRequestFocusEnabled(false);
        panel.add(time_txt6);
        time_txt6.setBounds(900, 0, 80, 20);

        date_txt6.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        date_txt6.setForeground(new java.awt.Color(255, 255, 255));
        date_txt6.setText("Date");
        panel.add(date_txt6);
        date_txt6.setBounds(900, 20, 80, 20);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("VIEW-PATIENT CASE RECORD");
        panel.add(jLabel2);
        jLabel2.setBounds(380, 10, 210, 30);
        panel.add(TextAge);
        TextAge.setBounds(650, 140, 60, 30);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name:");
        panel.add(jLabel3);
        jLabel3.setBounds(100, 150, 50, 17);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Date of Admission:");
        panel.add(jLabel7);
        jLabel7.setBounds(100, 200, 140, 30);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Address:");
        panel.add(jLabel9);
        jLabel9.setBounds(580, 190, 70, 30);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Sex:");
        panel.add(jLabel5);
        jLabel5.setBounds(760, 137, 30, 30);
        panel.add(TextAllergy);
        TextAllergy.setBounds(240, 360, 460, 60);

        TextContactNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextContactNoActionPerformed(evt);
            }
        });
        panel.add(TextContactNo);
        TextContactNo.setBounds(260, 250, 190, 30);

        TextAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextAddressActionPerformed(evt);
            }
        });
        panel.add(TextAddress);
        TextAddress.setBounds(650, 190, 240, 30);
        panel.add(TextOpno);
        TextOpno.setBounds(70, 50, 60, 30);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("OP.no:");
        panel.add(jLabel6);
        jLabel6.setBounds(20, 60, 50, 17);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Age:");
        panel.add(jLabel4);
        jLabel4.setBounds(580, 140, 40, 30);

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panel.add(jButton1);
        jButton1.setBounds(150, 50, 110, 30);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Contact No:");
        panel.add(jLabel8);
        jLabel8.setBounds(100, 250, 110, 30);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Drugs Allergy:");
        panel.add(jLabel10);
        jLabel10.setBounds(110, 370, 100, 30);
        panel.add(TextDateOfAdmission);
        TextDateOfAdmission.setBounds(260, 200, 190, 30);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Family Member:");
        panel.add(jLabel11);
        jLabel11.setBounds(100, 300, 110, 30);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Name:");
        panel.add(jLabel12);
        jLabel12.setBounds(220, 300, 50, 30);

        TextFName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFNameActionPerformed(evt);
            }
        });
        panel.add(TextFName);
        TextFName.setBounds(270, 300, 180, 30);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Contact No:");
        panel.add(jLabel13);
        jLabel13.setBounds(580, 300, 90, 30);

        TextFContactNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFContactNoActionPerformed(evt);
            }
        });
        panel.add(TextFContactNo);
        TextFContactNo.setBounds(680, 300, 210, 30);
        panel.add(TextSex);
        TextSex.setBounds(800, 140, 70, 30);
        panel.add(TextName);
        TextName.setBounds(150, 140, 290, 30);

        jButton6.setBackground(new java.awt.Color(204, 204, 204));
        jButton6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backbutton2.jpg"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        panel.add(jButton6);
        jButton6.setBounds(10, 10, 80, 27);

        Error.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Error.setForeground(new java.awt.Color(255, 0, 0));
        panel.add(Error);
        Error.setBounds(130, 424, 600, 40);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back.jpg"))); // NOI18N
        panel.add(jLabel1);
        jLabel1.setBounds(0, 0, 980, 600);

        add(panel);
        panel.setBounds(0, 0, 980, 600);

        jButton5.setBackground(new java.awt.Color(204, 204, 204));
        jButton5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backbutton2.jpg"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5);
        jButton5.setBounds(10, 10, 80, 27);
    }// </editor-fold>//GEN-END:initComponents

    private void TextAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextAddressActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int i = Integer.parseInt(TextOpno.getText());
        RepositoryClass Rc = new RepositoryClass();
        ResultSet rs = Rc.viewInPatient(i);
        try {
            if (rs.next()) {
                String add1 = rs.getString("Name");
                TextName.setText(add1);
                String add2 = rs.getString("Address");
                TextAddress.setText(add2);
                String add3 = rs.getString("Age");
                TextAge.setText(add3);
                String add4 = rs.getString("DateOfAdmission");
                TextDateOfAdmission.setText(add4);
                String add5 = rs.getString("Sex");
                TextSex.setText(add5);
                String add6 = rs.getString("ContactNo");
                TextContactNo.setText(add6);
                String add7 = rs.getString("FContactNo");
                TextFContactNo.setText(add7);
                String add8 = rs.getString("FamilyName");
                TextFName.setText(add8);
                String add9 = rs.getString("DrugsAllergy");
                TextAllergy.setText(add9);
                Error.setText("");

            } else {
                Error.setText("Sorry Patient Not Found !!!!");

                TextName.setText("");

                TextAddress.setText("");

                TextAge.setText("");

                TextDateOfAdmission.setText("");

                TextSex.setText("");
                TextContactNo.setText("");
                TextFName.setText("");
                TextFContactNo.setText("");
                TextAllergy.setText("");

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TextContactNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextContactNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextContactNoActionPerformed

    private void TextFNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFNameActionPerformed

    private void TextFContactNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFContactNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFContactNoActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        panel.removeAll();
        panel.setLayout(new GridLayout(1, 2));
        panel.add(new jpanel1());
        panel.updateUI();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        panel.removeAll();
        panel.setLayout(new GridLayout(1, 2));
        panel.add(new jpanel2());
        panel.updateUI();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Error;
    private javax.swing.JTextField TextAddress;
    private javax.swing.JTextField TextAge;
    private javax.swing.JTextField TextAllergy;
    private javax.swing.JTextField TextContactNo;
    private javax.swing.JTextField TextDateOfAdmission;
    private javax.swing.JTextField TextFContactNo;
    private javax.swing.JTextField TextFName;
    private javax.swing.JTextField TextName;
    private javax.swing.JTextField TextOpno;
    private javax.swing.JTextField TextSex;
    private javax.swing.JLabel date_txt6;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel time_txt6;
    // End of variables declaration//GEN-END:variables
}
